
meta_product_name: "Grow Garden"
meta_title: "Grow Garden - Help you grow your plants easily"
meta_description: "Grow Garden is a premuim app that takes care of your plants by sending you remainders with the your plants needs (water, temperature, light etc.)"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
